### ISSUE TITLE
To make available to rhel7

### ISSUE THREAD

**Issue by tumf** [tumf/ansible-role-systemd-service#1]

**Comment by tumf** [comment]
To make supported platforms which can be active systemd as default.

```
  platforms:
  - name: Ubuntu
    versions:
    - vivid
    - wily
  - name: EL
    versions:
    - 7
  - name: SLES
    versions:
    - 12
  - name: Debian
    versions:
    - jessie
  - name: Fedora
    versions:
    - 15
    - 16
    - 17
    - 18
    - 19
    - 20
    - 21
    - 22
```
