### ISSUE TITLE
Add include_role example

### ISSUE THREAD

**Issue by abh** [tumf/ansible-role-systemd-service#27]
I'm trying to use this from another role, but just get errors. A correct example in the readme would be helpful!

```
- name: setup nsd_exporter service
  include_role:
    name: tumf.systemd-service
  vars:
    systemd_service_name: "nsd_exporter"
    systemd_service_Service_ExecStart: "/opt/bin/nsd_exporter"
```

gives me this error:

```
ERROR! Invalid options for include_role: systemd_service_Service_ExecStart,systemd_service_name
```

I realize this isn't a problem with the role but really me not understanding the ansible documentation, but I thought still an example in the README here would be useful as I am guessing this might be a common use case. :-)
